DROP TABLE IF EXISTS hits;

CREATE TABLE IF NOT EXISTS hits
(
    hit_id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    app varchar NOT NULL,
    uri varchar NOT NULL,
    ip varchar NOT NULL,
    created TIMESTAMP NOT NULL
);